/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { CaseModelService } from "../caseModel.service";
import { CaseModelCreateInput } from "./CaseModelCreateInput";
import { CaseModel } from "./CaseModel";
import { CaseModelFindManyArgs } from "./CaseModelFindManyArgs";
import { CaseModelWhereUniqueInput } from "./CaseModelWhereUniqueInput";
import { CaseModelUpdateInput } from "./CaseModelUpdateInput";

export class CaseModelControllerBase {
  constructor(protected readonly service: CaseModelService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: CaseModel })
  async createCaseModel(
    @common.Body() data: CaseModelCreateInput
  ): Promise<CaseModel> {
    return await this.service.createCaseModel({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [CaseModel] })
  @ApiNestedQuery(CaseModelFindManyArgs)
  async caseModels(@common.Req() request: Request): Promise<CaseModel[]> {
    const args = plainToClass(CaseModelFindManyArgs, request.query);
    return this.service.caseModels({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: CaseModel })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async caseModel(
    @common.Param() params: CaseModelWhereUniqueInput
  ): Promise<CaseModel | null> {
    const result = await this.service.caseModel({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: CaseModel })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateCaseModel(
    @common.Param() params: CaseModelWhereUniqueInput,
    @common.Body() data: CaseModelUpdateInput
  ): Promise<CaseModel | null> {
    try {
      return await this.service.updateCaseModel({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: CaseModel })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteCaseModel(
    @common.Param() params: CaseModelWhereUniqueInput
  ): Promise<CaseModel | null> {
    try {
      return await this.service.deleteCaseModel({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
